### ISSUE TITLE
No candidate version available error when installing custom package with this cookbook

### ISSUE THREAD

**Issue by mistroh** [bakins/cookbook-gdebi#8]
Hello,

I'm trying to use this cookbook to install a deb package that is internal to our organization on Ubuntu box.  When using this cookbook to install the package, I get the following error.  I am able to run "sudo gdebi packagename.deb" on the box and install the package.  Any ideas on what I'm missing?  Thanks

    * No candidate version available for /var/tmp/packagename.deb
    ================================================================================
    Error executing action `install` on resource 'gdebi_package[/var/tmp/packagename.deb]'

**Comment by bakins** [comment]
If you try with debug log on, do you get any more info?

Also, what version of chef?

**Comment by mistroh** [comment]
Hi,

Version of Chef is 12.7.2.

I'm not 100% sure how to turn debug logging on.  I added the following to my recipe, which I believe from the Chef docs should turn debug logging on:

```
log 'a debug string' do
  level :debug
end
```

This was the output:

     * No candidate version available for /var/tmp/packagename_0.0.1_amd64.deb
     ================================================================================
     Error executing action `install` on resource 'gdebi_package[/var/tmp/packagename_0.0.1_amd64.deb]'
     ================================================================================

     Chef::Exceptions::Package
     -------------------------
     No candidate version available for /var/tmp/packagename_0.0.1_amd64.deb

 Resource Declaration:
     ---------------------
     # In /tmp/kitchen/cache/cookbooks/CookbookName/recipes/CookbookName.rb

      gdebi_package '/var/tmp/packagename_0.0.1_amd64.deb' do
        action :install
        version '0.0.1'
      end
      
       Compiled Resource:
       ------------------
       # Declared in /tmp/kitchen/cache/cookbooks/CookbookName/recipes/CookbookName.rb:49:in `from_file'

       gdebi_package("/var/tmp/packagename_0.0.1_amd64.deb") do
         package_name "/var/tmp/packagename_0.0.1_amd64.deb"
         provider Chef::Provider::Package::Gdebi
         action [:install]
         retries 0
         retry_delay 2
         default_guard_interpreter :default
         declared_type :gdebi_package
         cookbook_name "CookbookName"
         recipe_name "CookbookName"
         version "0.0.1"
       end

   Running handlers:
   [2016-02-23T18:55:20+00:00] ERROR: Running exception handlers
   Running handlers complete

   Chef Client failed. 1 resources updated in 01 seconds
   [2016-02-23T18:55:20+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
   [2016-02-23T18:55:20+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report

   [2016-02-23T18:55:20+00:00] ERROR: gdebi_package[/var/tmp/packagename_0.0.1_amd64.deb] (CookbookName::CookbookName line 49) had an error: Chef::Exceptions::Package: No candidate version available for /var/tmp/packageName.1_amd64.deb
   [2016-02-23T18:55:20+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully ( code 1)
>> Converge failed on instance <default-ubuntu-1404>.

Thanks.

**Comment by bakins** [comment]
something like `chef --log_level debug` ? I haven't done chef stuff in a while.

**Comment by mistroh** [comment]
You're correct.  I did run `chef-client -l debug`

Below is the output:

`DEBUG: {"action"=>"end", "resources"=>[{"type"=>:execute, "name"=>"apt-get update", "id"=>"apt-get update", "after"=>{:command=>"apt-get update"}, "before"=>{}, "duration"=>"6034", "delta"=>"", "result"=>"run", "cookbook_name"=>"apt", "cookbook_version"=>"2.9.2"}, {"type"=>:file, "name"=>"/var/lib/apt/periodic/update-success-stamp", "id"=>"/var/lib/apt/periodic/update-success-stamp", "after"=>{:owner=>"root", :group=>"root", :mode=>"0644", :path=>"/var/lib/apt/periodic/update-success-stamp"}, "before"=>{:owner=>"root", :group=>"root", :mode=>"0644", :path=>"/var/lib/apt/periodic/update-success-stamp"}, "duration"=>"4", "delta"=>"", "result"=>"touch", "cookbook_name"=>"apt", "cookbook_version"=>"2.9.2"}, {"type"=>:gdebi_package, "name"=>"/var/tmp/internal-api_0.0.1_amd64.deb", "id"=>"/var/tmp/internal-api_0.0.1_amd64.deb", "after"=>{:package_name=>"/var/tmp/internal-api_0.0.1_amd64.deb", :version=>"0.0.1"}, "before"=>{:package_name=>"/var/tmp/internal-api_0.0.1_amd64.deb"}, "duration"=>"5", "delta"=>"", "result"=>"install", "cookbook_name"=>"SharedServicesInstall", "cookbook_version"=>"0.1.8"}], "status"=>"failure", "run_list"=>"[\"recipe[chef-client]\",\"recipe[SharedServicesInstall]\"]", "total_res_count"=>"25", "data"=>{"exception"=>{"class"=>"#<Chef::Exceptions::Package: gdebi_package[/var/tmp/internal-api_0.0.1_amd64.deb] (SharedServicesInstall::SharedServices line 45) had an error: Chef::Exceptions::Package: No candidate version available for /var/tmp/internal-api_0.0.1_amd64.deb>", "message"=>"gdebi_package[/var/tmp/internal-api_0.0.1_amd64.deb] (SharedServicesInstall::SharedServices line 45) had an error: Chef::Exceptions::Package: No candidate version available for /var/tmp/internal-api_0.0.1_amd64.deb", "backtrace"=>"[\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/mixin/why_run.rb:240:in `run'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/mixin/why_run.rb:321:in `block in run'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/mixin/why_run.rb:320:in `each'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/mixin/why_run.rb:320:in `run'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/provider.rb:154:in `process_resource_requirements'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/provider.rb:132:in `run_action'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/resource.rb:596:in `run_action'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/runner.rb:73:in `run_action'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/runner.rb:105:in `block (2 levels) in converge'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/runner.rb:105:in `each'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/runner.rb:105:in `block in converge'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/runner.rb:104:in `converge'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/client.rb:668:in `block in converge'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/client.rb:663:in `catch'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/client.rb:663:in `converge'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/client.rb:702:in `converge_and_save'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/client.rb:280:in `run'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application.rb:270:in `block in fork_chef_client'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application.rb:258:in `fork'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application.rb:258:in `fork_chef_client'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application.rb:223:in `block in run_chef_client'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/local_mode.rb:44:in `with_server_connectivity'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application.rb:211:in `run_chef_client'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application/client.rb:433:in `block in interval_run_chef_client'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application/client.rb:423:in `loop'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application/client.rb:423:in `interval_run_chef_client'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application/client.rb:412:in `run_application'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application.rb:58:in `run'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/bin/chef-client:26:in `<top (required)>'\",\"/usr/bin/chef-client:50:in `load'\",\"/usr/bin/chef-client:50:in `<main>'\"]", "description"=>{"title"=>"Error executing action `install` on resource 'gdebi_package[/var/tmp/internal-api_0.0.1_amd64.deb]'", "sections"=>[{"Chef::Exceptions::Package"=>"No candidate version available for /var/tmp/internal-api_0.0.1_amd64.deb"}, {"Resource Declaration:"=>"# In /var/chef/cache/cookbooks/SharedServicesInstall/recipes/SharedServices.rb\n\n 45: gdebi_package '/var/tmp/internal-api_0.0.1_amd64.deb' do\r\n 46:   action :install\r\n 47:   version '0.0.1' \r\n 48: end\r\n 49: \r\n"}, {"Compiled Resource:"=>"# Declared in /var/chef/cache/cookbooks/SharedServicesInstall/recipes/SharedServices.rb:45:in `from_file'\n\ngdebi_package(\"/var/tmp/internal-api_0.0.1_amd64.deb\") do\n  package_name \"/var/tmp/internal-api_0.0.1_amd64.deb\"\n  provider Chef::Provider::Package::Gdebi\n  action [:install]\n  retries 0\n  retry_delay 2\n  default_guard_interpreter :default\n  declared_type :gdebi_package\n  cookbook_name \"SharedServicesInstall\"\n  recipe_name \"SharedServices\"\n  version \"0.0.1\"\nend\n"}]}}}, "start_time"=>"2016-02-23 23:23:36 +0000", "end_time"=>"2016-02-23 23:23:43 +0000", "expanded_run_list"=>"{\"id\":\"_default\",\"run_list\":[{\"type\":\"recipe\",\"name\":\"chef-client\",\"version\":null,\"skipped\":false},{\"type\":\"recipe\",\"name\":\"SharedServicesInstall\",\"version\":null,\"skipped\":false}]}"}
`

**Comment by bakins** [comment]
Maybe try something like:

```
gdebi_package 'mypackage' do
  source '/path/to/my/package.deb;
end
```

**Comment by mistroh** [comment]
Thanks for the suggestions. I think that format helped.  I'm still getting errors with the install, but it might be on my end and a problem with the package.  I'll look into it more and post again if I need additional help.  Thanks.
